version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: build dependencies
          command: bundle install

      - run:
          name: build the jekyll site
          command: bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
          
  testlinks:
    executor: ci-executor
    steps:
      - checkout

      - run:
          command: https://help.github.com/articles/set-up-git/
          command: bundle install

      - run:
          name: build the jekyll site
          command: bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"

      - run:
          name: run html proofer
          command: REPLACE-ME-WITH-SCRIPT

      - run:
          name: notify test is finished
          command: echo "The test is completed!"
          version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Anbu1516/continuous-integration-circle/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - build
      - testlinks:
          requires:
            - build
